### ISSUE TITLE
Add hidden fields "medium" and "campaign" to support more parameter tracking

### ISSUE THREAD

**Issue by adamsfallen** [presidential-innovation-fellows/pif-application#1]
Based on Nathan request to better track applicants as they move through funnel, we discussed adding a couple hidden fields to the form - "campaign" (e.g. roadshow) and "medium" (e.g. email/web) - that we'd support with URL parameters.

**Comment by rossdakin** [comment]
I would suggest using the GA "UTM" conventions:

E.g. https://raventools.com?utm_source=s&utm_medium=m&utm_campaign=n&utm_term=t&utm_content=c

https://raventools.com/gaconfig/google-analytics-url-builder/

**Comment by adamsfallen** [comment]
Roger good point and will do.

**Comment by stroupaloop** [comment]
Should be resolved and implemented
